name: DETAiLFILM
favicon: null
layout_spectrum: 0.00501
typography_spectrum: 0.26544
title: DETAiLFILM
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f2f1ed'
    - '#060606'
    - '#7f7f7f'
    - '#515151'
    - '#f90008'
  brandStrength: 0.4375
  lightness: 0.8125
  saturation: 0.375
  rhythmicContrast: 1
purpose: []
