name: DETAiLFILM
favicon: null
layout_spectrum: 0.2404
typography_spectrum: 0.61436
title: DETAiLFILM
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f2f1ed'
    - '#060606'
    - '#7f7f7f'
    - '#515151'
    - '#f90008'
  brandStrength: 0.6875
  lightness: 0.6875
  saturation: 0.3125
  rhythmicContrast: 1
purpose: []
