name: DETAiLFILM
favicon: null
layout_spectrum: 0.35726
typography_spectrum: 0.61436
title: DETAiLFILM
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#324446'
    - '#637977'
    - '#fbffff'
    - '#a9b4b3'
  brandStrength: 0.5
  lightness: 0.625
  saturation: 0.125
  rhythmicContrast: 1
purpose: []
