name: DETAiLFILM
favicon: null
layout_spectrum: 0.08834755630232394
typography_spectrum: 0.28879739926196635
title: DETAiLFILM
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.0625
  lightness: 0.6875
  saturation: 0.4375
  rhythmicContrast: 1
purpose: []
